In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('customer.csv')

In [3]:
df.sample(5)

age  gender   review education purchased
9    74    Male     Good        UG       Yes
44   77  Female  Average        UG        No
39   76    Male     Poor        PG        No
21   32    Male  Average        PG        No
7    60  Female     Poor    School       Yes

In [4]:
df = df.iloc[:,2:]

In [7]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [33]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:2], df.iloc[:,-1], test_size =0.3)

In [34]:
X_train

review education
36     Good        UG
14     Poor        PG
2      Good        PG
16     Poor        UG
19     Poor        PG
18     Good    School
33     Good        PG
40     Good    School
38     Good    School
23     Good    School
41     Good        PG
28     Poor    School
24  Average        PG
8   Average        UG
34  Average    School
43     Poor        PG
17     Poor        UG
44  Average        UG
11     Good        UG
13  Average    School
29  Average        UG
5   Average    School
10     Good        UG
4   Average        UG
6      Good    School
49     Good        UG
9      Good        UG
7      Poor    School
0   Average    School
31     Poor    School
3      Good        PG
26     Poor        PG
39     Poor        PG
25     Good    School
30  Average        UG

In [35]:
from sklearn.preprocessing import OrdinalEncoder

In [36]:
oe = OrdinalEncoder(categories = [['Poor', 'Average', 'Good'] ,['School','UG','PG']])

In [37]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [38]:
X_train  = oe.transform(X_train)

In [39]:
X_train

array([[2., 1.],
       [0., 2.],
       [2., 2.],
       [0., 1.],
       [0., 2.],
       [2., 0.],
       [2., 2.],
       [2., 0.],
       [2., 0.],
       [2., 0.],
       [2., 2.],
       [0., 0.],
       [1., 2.],
       [1., 1.],
       [1., 0.],
       [0., 2.],
       [0., 1.],
       [1., 1.],
       [2., 1.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [2., 1.],
       [1., 1.],
       [2., 0.],
       [2., 1.],
       [2., 1.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [2., 2.],
       [0., 2.],
       [0., 2.],
       [2., 0.],
       [1., 1.]])

In [43]:
oe.categories

[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']]

In [40]:
X_test = oe.transform(X_test)

In [41]:
X_test

array([[0., 2.],
       [0., 2.],
       [1., 2.],
       [0., 1.],
       [2., 1.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [1., 2.],
       [2., 2.],
       [0., 1.],
       [1., 1.],
       [0., 0.],
       [0., 2.],
       [1., 0.]])

In [44]:
from sklearn.preprocessing import LabelEncoder

In [45]:
le = LabelEncoder()

In [46]:
le.fit(y_train)

LabelEncoder()

In [48]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [49]:
y_train = le.transform(y_train)

In [50]:
y_test = le.transform(y_test)

In [51]:
y_train

array([1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0])