In [1]:
import pickle
import numpy as np

In [3]:
ohe_sex = pickle.load(open('model/ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('model/ohe_embarked.pkl','rb'))
clf = pickle.load(open('model/clf.pkl','rb'))

In [4]:
# Assume user input
# Pclass/gender/age/SibSp/Parch/Fare/Embarked
test_input = np.array([2, 'male', 31.0, 0, 0, 10.5, 'S'],dtype=object).reshape(1,7)

In [5]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [6]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))


E:\Ambu_newPython_06.08.2024\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [7]:
test_input_sex


array([[0., 1.]])

In [8]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))


In [9]:
test_input_embarked


array([[0., 0., 1.]])

In [10]:
test_input_age = test_input[:,2].reshape(1,1)


In [11]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)


In [12]:
test_input_transformed.shape


(1, 10)

In [13]:
clf.predict(test_input_transformed)


array([1])