In [13]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.tree import DecisionTreeClassifier

In [14]:
df = pd.read_csv("train.csv")

In [15]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [16]:
df = df.drop(columns = ['PassengerId' , 'Name',	'Ticket', 'Cabin'])

In [17]:
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns = ['Survived']), df['Survived'] , test_size = 0.3 , random_state =24) 

In [19]:
X_train.head(2)

Pclass     Sex   Age  SibSp  Parch    Fare Embarked
855       3  female  18.0      0      1  9.3500        S
499       3    male  24.0      0      0  7.7958        S

In [22]:
si_age = SimpleImputer()

In [23]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [25]:
si_embarked = SimpleImputer(strategy = 'most_frequent')

In [27]:
X_train_age = si_age.fit_transform(X_train[['Age']])
X_train_embarked = si_embarked.fit_transform(X_train[['Embarked']])
X_test_age = si_age.transform(X_test[['Age']])
X_test_embarked = si_embarked.transform(X_test[['Embarked']])

In [28]:
ohe_sex = OneHotEncoder(sparse_output = False)
ohe_embarked = OneHotEncoder(sparse_output = False)
X_train_sex = ohe_sex.fit_transform(X_train[['Sex']])
X_train_embarked = ohe_embarked.fit_transform(X_train_embarked)

X_test_sex = ohe_sex.fit_transform(X_test[['Sex']])
X_test_embarked = ohe_embarked.fit_transform(X_test_embarked)

In [29]:
X_train_sex

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       ...,
       [0., 1.],
       [1., 0.],
       [0., 1.]])

In [30]:
X_train_embarked

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [31]:
X_train_rem = X_train.drop(columns = ['Sex' , 'Age', 'Embarked'])

In [32]:
X_train_rem

Pclass  SibSp  Parch     Fare
855       3      0      1   9.3500
499       3      0      0   7.7958
799       3      1      1  24.1500
177       1      0      0  28.7125
617       3      1      0  16.1000
..      ...    ...    ...      ...
145       2      1      1  36.7500
401       3      0      0   8.0500
343       2      0      0  13.0000
192       3      1      0   7.8542
418       2      0      0  13.0000

[623 rows x 4 columns]

In [33]:
X_test_rem = X_test.drop(columns = ['Sex' , 'Age', 'Embarked'])

In [35]:
X_train_transformed = np.concatenate((X_train_rem, X_train_age, X_train_sex,X_train_embarked), axis = 1)
X_test_transformed = np.concatenate ((X_test_rem, X_test_age, X_test_sex, X_test_embarked), axis = 1)

In [36]:
X_train_transformed

array([[3., 0., 1., ..., 0., 0., 1.],
       [3., 0., 0., ..., 0., 0., 1.],
       [3., 1., 1., ..., 0., 0., 1.],
       ...,
       [2., 0., 0., ..., 0., 0., 1.],
       [3., 1., 0., ..., 0., 0., 1.],
       [2., 0., 0., ..., 0., 0., 1.]])

In [38]:
clf = DecisionTreeClassifier()
clf.fit(X_train_transformed, y_train)

DecisionTreeClassifier()

In [40]:
predii =clf.predict(X_test_transformed)
predii

array([1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1])

In [44]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, predii)

0.7313432835820896

In [45]:
import pickle

In [47]:
pickle.dump(ohe_sex,open('model/ohe_sex.pkl','wb'))
pickle.dump(ohe_embarked,open('model/ohe_embarked.pkl','wb'))
pickle.dump(clf,open('model/clf.pkl','wb'))